# Site settings
title: DarkGenesis - indie development for the new world order
description: >- # this means to ignore newlines until "baseurl:"
  Indie development blog for the new world order.
  Featuring blogs, tutorials and content all geared around Mixed Reality and beyond
  As well as a touch of Game Development and services :D 
permalink: ':title:output_ext'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://simondarksidej.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/img/branding/darkgenesis-logo-full-light.png"
logo-icon: "/assets/img/branding/ZenithMoonLogo.png"
logo-icon-SEO: "/assets/img/branding/ZenithMoonLogo.png" # must be a non SVG file
logo-dark: "/assets/img/branding/darkgenesis-logo-full-dark.png"

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is "manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
night_mode: "auto"

highlight_theme: syntax-base16.monokai.dark # select a dark theme for the code highlighter if needed

# Author settings
author: Simon (darkside) Jackson
author-pic: Myself_grey.jpg
about-author: Engineer, industry executive, research enthusiast. Avid learner with diverse interests in coding, game development, Mixed Reality (AR/VR/XR) and reinforcement learning. 25+ years of experience working in multinational corporations and startups.

# Contact links
email: darkside@zenithmoon.com
phone: # Add your Phone number
website: https://darkgenesis.zenithmoon.com # Add your website
linkedin: simonjacksonsdj # Add your Linkedin handle
github: simondarksidej # Add your Github handle
twitter: '@simondarksidej' # Add your Twitter handle
bandcamp:  # Add your Bandcamp username
stackoverflow: darkside # Add your stackoverflow account

# Newsletter
mailchimp: #"https://github.us1.list-manage.com/subscribe/post?u=8ece198b3eb260e6838461a60&amp;id=397d90b5f4"

# Disqus
discus_identifier: #amaynez-github-io # Add your discus identifier
comments_curtain: no # leave empty to show the disqus embed directly

# Tracker
analytics: #G-R8SZS2YBZK
fbadmin: #ar.maybach

# Paginate
paginate: 8
paginate_path: 'page:num'
words_per_minute: 200

# Build settings
markdown: kramdown
mathjax: true
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Outputting
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

category_archive:
  type: liquid
  path: /categories/

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]

jekyll_compose:
  auto_open: true
  default_front_matter:
    drafts:
      description:
      img: posts/defaultpostimage.jpg
      category:
      tags: []
      author: Simon Jackson
      github:  
      mathjax: no      
    posts:
      description:
      img: posts/
      category:
      tags: []
      author: Simon Jackson
      github:  
      mathjax: no      
      published: false
      sitemap: false
      read_time: true
      show_date: true
